config/routes.rb
Rails.application.routes.draw do
  resources :provinces
  resources :projects do
    resources :tasks
  end

  resources :cantons

# /projects/:project_id/tasks
 # namespace :project do
 #   resources :tasks
 # end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/canton.rb
class Canton < ApplicationRecord
    belongs_to :province
    has_many :cantons
        
end

app/models/district.rb
class District < ApplicationRecord
    belongs_to :canton
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  belongs_to :user
end

app/models/province.rb
class Province < ApplicationRecord
    validates :status, inclusion: { in: ['1', '2', '3', '4', '5', '6', '7']}
    has_many :cantons
    STATUS_OPTIONS = [
      ['San José','1'],
      ['Alajuela','2'],
      ['Cartago','3'],
      ['Heredia','4'],
      ['Guanacaste','5'],
      ['Puntarenas','6'],
      ['Limón','7'],      
    ]
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  validates :status, inclusion: { in: ['not-started', 'in-progress', 'complete']}
  
  STATUS_OPTIONS = [
    ['Not started','not-started'],
    ['In progress','in-progress'],
    ['Complete','complete'],
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cantons_controller.rb
class CantonsController < ApplicationController
    before_action :set_province

    def index

        #puts = depurando
        @canton = puts: "Holas"

        @cantons = Canton.select(:name, :code).where(provinceCode: params[:province_id])
    end

    #def options
    #    if params[:province_id] == 1
    #        @cantons = Canton.select(:name, :code).where(provinceCode: 1)
    #    else if params[:province_id] == 2
    #        @cantons = Canton.select(:name, :code).where(provinceCode: 2)
    #    else if params[:province_id] == 3
    #        @cantons = Canton.select(:name, :code).where(provinceCode: 3)
    #    else if params[:province_id] == 4
    #        @cantons = Canton.select(:name, :code).where(provinceCode: 4)
    #    else if params[:province_id] == 5
    #        @cantons = Canton.select(:name, :code).where(provinceCode: 5)
    #    else if params[:province_id] == 6
    #        @cantons = Canton.select(:name, :code).where(provinceCode: 6)
    #    else if params[:province_id] == 7
    #        @cantons = Canton.select(:name, :code).where(provinceCode: 7)
    #    end
    #end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1 or /projects/1.json
  def show
    @task =  @project.tasks.build
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  before_action :set_province, only: %i[ show edit update destroy ]

  # GET /provinces or /provinces.json
  def index
    @provinces = Province.all
  end

  # GET /provinces/1 or /provinces/1.json
  def show
  end

  # GET /provinces/new
  def new
    @province = Province.new
  end

  # GET /provinces/1/edit
  def edit
  end

  # POST /provinces or /provinces.json
  def create
    @province = Province.new(province_params)

    respond_to do |format|
      if @province.save
        format.html { redirect_to province_url(@province), notice: "Province was successfully created." }
        format.json { render :show, status: :created, location: @province }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provinces/1 or /provinces/1.json
  def update
    respond_to do |format|
      if @province.update(province_params)
        format.html { redirect_to province_url(@province), notice: "Province was successfully updated." }
        format.json { render :show, status: :ok, location: @province }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provinces/1 or /provinces/1.json
  def destroy
    @province.destroy

    respond_to do |format|
      format.html { redirect_to provinces_url, notice: "Province was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_province
      @province = Province.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def province_params
      params.fetch(:province, {})
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET projects/1/tasks
  def index
    @tasks = @project.tasks
  end

  # GET projects/1/tasks/1
  def show
  end

  # GET projects/1/tasks/new
  def new
    @task = @project.tasks.build
  end

  # GET projects/1/tasks/1/edit
  def edit    
  end

  # POST projects/1/tasks
  def create
    @task = @project.tasks.build(task_params)

    if @task.save
      redirect_to(@task.project)
      flash[:succes] = "Tarea agregada con éxito!"
    else
      render action: 'new'
    end
  end

  # PUT projects/1/tasks/1
  def update
    if @task.update(task_params)
      redirect_to(@task.project)
      flash[:succes] = "Tarea actualizada!"
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
    @task.destroy

    redirect_to @project
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:project_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :description, :status, :dead_line, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/canton_helper.rb
module CantonHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimplePm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-pt5">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <div class="card">
        <div class="card-body">
        <%= yield %>
        </div> 
      </div>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="card">
  <div class="card-body">
    <h2 class='card-title d-flex justify-content-between'>
      <span>Proyectos</span>
      <%= link_to 'Nuevo Proyecto', new_project_path, class: 'btn btn-primary' %>
    </h2>

    <% @projects.each do |project| %>
      <%= link_to project do %>
        <div class="card">
            <div class="card-body">
            
              <h5 class= 'card-title'><%= project.name %></h5>
              <p><%= project.description %></p>

              <p><h5 class= 'card-title'>Propietario del proyecto</h5></p>
              <p><%= project.user.name %> </p>
              

              <p><h5 class= 'card-title'>número interno:</h5></p>
              <p><%= project.user_id %> </p>
               
              
            </div>
        </div>
     <% end %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="card">
  <div class="card-body">
    <h2 class='card-title d-flex justify-content-between'>
      <span><%= @project.name %></span>
      
    </h2>
  </div>
</div>

<p>
  <strong>Nombre:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Usuario id:</strong>
  <%= @project.user_id %>
<br>
<br>
  <strong>Usuario name:</strong>
  <%= @project.user.name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %>
<%= link_to 'Back', projects_path %>

<hr>

<h1>Nueva task</h1>

<%= render 'tasks/form' %>



<hr>
<th>Provincia </th>
<select name="provinces[province_Code]" id="province">
  <option value="1">San José</option>
  <option value="2">Alajuela</option>
  <option value="3">Cartago</option>
  <option value="4">Heredia</option>
  <option value="5">Guanacaste</option>
  <option value="6">Puntarenas</option>
  <option value="7">Limón</option>
  
</select>

<th>Cantón </th>
<select name="cantons" id="canton">
</select>

<br>
<hr>

<h1>Lista tasks</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripción</th>
    <th>Estado</th>
    <th>Proyecto</th>
    <th>Fecha Limite</th>
    <th></th>
    <th></th>
  </tr>

<% @project.tasks.each do |task| %>
  <% if task.persisted? %>
    <tr>
      <td><%= task.name %></td>
      <td><%= task.description %></td>
      <td><%= task.status %></td>
      <td><%= task.project.name %></td>
      <td><%= task.dead_line %></td>
      <td><%= link_to 'Show', [task.project, task] %></td>
      <td><%= link_to 'Edit', edit_project_task_path(task.project, task) %></td>
      <td><%= link_to 'Destroy', [task.project, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>  
<% end %>
</table>

<br />

<%= link_to 'New Task', new_project_task_path(@project.id) %>

app/views/provinces/_form.html.erb
<%= form_with(model: province) do |f| %>
  <% if province.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(province.errors.count, "error") %> prohibited this province from being saved:</h2>

      <ul>
        <% province.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Provincia %><br />
    <%= f.select :status, Province::STATUS_OPTIONS %>
  </div>
<% end %>

app/views/provinces/edit.html.erb
<h1>Editing Province</h1>

<%= render 'form', province: @province %>

<%= link_to 'Show', @province %> |
<%= link_to 'Back', provinces_path %>

app/views/provinces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Provinces</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provinces.each do |province| %>
      <tr>
        <td><%= link_to 'Show', province %></td>
        <td><%= link_to 'Edit', edit_province_path(province) %></td>
        <td><%= link_to 'Destroy', province, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Province', new_province_path %>

app/views/provinces/new.html.erb
<h1>New Province</h1>

<%= render 'form', province: @province %>

<%= link_to 'Back', provinces_path %>

app/views/provinces/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_province_path(@province) %> |
<%= link_to 'Back', provinces_path %>

app/views/tasks/_form.html.erb
<%= form_with(model: [@task.project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
  <%= f.label :Entrega %><br />
  <%= f.text_field :dead_line %>
</div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, Task::STATUS_OPTIONS %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
  <br>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', [@task.project, @task] %> |
<%= link_to 'Back', project_tasks_path(@task.project) %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th>Project</th>
    <th>Entrega</th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= task.status %></td>
    <td><%= task.project %></td>
    <td><%= task.dead_line %></td>
    <td><%= link_to 'Show', [task.project, task] %></td>
    <td><%= link_to 'Edit', edit_project_task_path(task.project, task) %></td>
    <td><%= link_to 'Destroy', [task.project, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_project_task_path(params[:project_id]) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', project_tasks_path(@task.project) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Project:</b>
  <%= @task.project %>
</p>

<p>
  <b>Entrega:</b>
  <%= @task.dead_line %>
</p>

<%= link_to 'Edit', edit_project_task_path(@task.project, @task) %> |
<%= link_to 'Back', project_tasks_path(@task.project) %>